name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest # Arm based macs
            args: --target aarch64-apple-darwin
          - platform: macos-latest # Intel based macs
            args: --target x86_64-apple-darwin
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23.5.0

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Targets for Mac builds only
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: nuxtor-v__VERSION__
          releaseName: Nuxtor v__VERSION__
          releaseBody: After installing the Apple app you have to run "xattr -c /Applications/Nuxtor.app" once before launching
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

      - name: Generate latest.json
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/nuxtor-v//')
          cat <<EOF > latest.json
          {
            "version": "$VERSION",
            "notes": "Bug fixes and improvements.",
            "pub_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "platforms": {
              "windows-x86_64": {
                "signature": "SIGNATURE_STRING",
                "url": "https://github.com/jotapebatista/label-printer-app/releases/download/nuxtor-v$VERSION/Barix.-.Label.Printer.App_${VERSION}_x64-setup.exe"
              },
              "darwin-x86_64": {
                "signature": "SIGNATURE_STRING",
                "url": "https://github.com/jotapebatista/label-printer-app/releases/download/nuxtor-v$VERSION/Barix.-.Label.Printer.App_${VERSION}_x64.dmg"
              },
              "linux-x86_64": {
                "signature": "SIGNATURE_STRING",
                "url": "https://github.com/jotapebatista/label-printer-app/releases/download/nuxtor-v$VERSION/Barix.-.Label.Printer.App_${VERSION}_amd64.deb"
              }
            }
          }
          EOF

      - name: Upload latest.json to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: latest.json
          tag_name: nuxtor-v__VERSION__
