name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
            artifact: Barix.-.Label.Printer.App_${VERSION}_aarch64.dmg
          - platform: macos-latest
            target: x86_64-apple-darwin
            artifact: Barix.-.Label.Printer.App_${VERSION}_x64.dmg
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            artifact: Barix.-.Label.Printer.App_${VERSION}_amd64.deb
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: Barix.-.Label.Printer.App_${VERSION}_x64-setup.exe

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23.5.0

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: nuxtor-v__VERSION__
          releaseName: Nuxtor v__VERSION__
          releaseBody: After installing the Apple app you have to run "xattr -c /Applications/Nuxtor.app" once before launching
          releaseDraft: false
          prerelease: false
          args: --target ${{ matrix.target }}

      - name: Extract Tauri signature
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/nuxtor-v//')
          SIGNATURE=$(cat src-tauri/target/release/bundle/${{ matrix.target }}/signature.txt)

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SIGNATURE=$SIGNATURE" >> $GITHUB_ENV

      - name: Generate latest.json
        run: |
          cat <<EOF > latest.json
          {
            "version": "$VERSION",
            "notes": "Bug fixes and improvements.",
            "pub_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "platforms": {
              "${{ matrix.target }}": {
                "signature": "$SIGNATURE",
                "url": "https://github.com/jotapebatista/label-printer-app/releases/download/nuxtor-v$VERSION/${{ matrix.artifact }}"
              }
            }
          }
          EOF

      - name: Upload latest.json to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: latest.json
          tag_name: nuxtor-v__VERSION__
